2024-04-27 23:17:27,592 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-04-27 23:17:55,120 [INFO] in django.utils.autoreload: /mnt/c/Users/user/MySitee/MySitee/mysite/mysite/settings.py changed, reloading.
2024-04-30 12:56:01,513 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-04-30 12:56:26,159 [INFO] in django.utils.autoreload: C:\Users\user\Desktop\Django_project\mysite\shopapp\views.py changed, reloading.
2024-04-30 12:56:26,851 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-04-30 12:56:30,113 [WARNING] in django.request: Not Found: /ru/
2024-05-01 11:56:58,145 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 11:57:00,897 [WARNING] in django.request: Not Found: /ru/
2024-05-01 11:57:01,105 [WARNING] in django.request: Not Found: /ru/favicon.ico
2024-05-01 12:01:16,746 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:01:17,463 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:01:23,182 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:01:24,053 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:01:26,533 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:01:27,240 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:01:45,418 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:01:46,093 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:02:41,990 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:02:42,573 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:03:22,838 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:03:23,621 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:03:47,064 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:03:47,676 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:04:06,708 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:04:07,410 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:04:34,323 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-01 12:04:34,961 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:05:19,435 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:05:20,356 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:06:27,558 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:06:28,183 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:07:08,591 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:07:09,180 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:07:24,268 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:07:24,900 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:08:04,211 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:08:04,855 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:08:18,910 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:08:19,524 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:08:46,221 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:08:46,849 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:09:42,738 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:09:43,338 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:09:57,263 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:09:57,967 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:13:20,954 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject2\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-01 12:13:21,914 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:13:36,923 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:13:41,588 [WARNING] in django.request: Not Found: /ru/
2024-05-03 16:52:12,245 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 16:59:13,969 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 16:59:17,465 [WARNING] in django.request: Not Found: /ru/
2024-05-03 16:59:17,619 [WARNING] in django.request: Not Found: /ru/favicon.ico
2024-05-03 16:59:23,601 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 16:59:24,215 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 17:00:19,246 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 17:00:21,244 [WARNING] in django.request: Not Found: /ru/
2024-05-03 17:00:28,248 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 17:00:31,851 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 17:01:56,355 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 17:01:58,007 [WARNING] in django.request: Not Found: /ru/
2024-05-03 17:02:03,711 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 17:02:04,328 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2024-05-03 17:03:47,584 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 17:03:49,043 [WARNING] in django.request: Not Found: /ru/
2024-05-03 17:03:54,097 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    raise TemplateSyntaxError("'%s' tag takes only one argument" % bits[0])
django.template.exceptions.TemplateSyntaxError: 'block' tag takes only one argument
2024-05-03 17:03:54,421 [ERROR] in django.request: Internal Server Error: /ru/shop/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject7\Django_project\mysite\shopapp\views.py", line 70, in shop_index
    return render(request, 'shopapp/index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 222, in do_block
    raise TemplateSyntaxError("'%s' tag takes only one argument" % bits[0])
django.template.exceptions.TemplateSyntaxError: 'block' tag takes only one argument
2024-05-03 17:11:27,779 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 17:11:29,489 [WARNING] in django.request: Not Found: /ru/
2024-05-03 17:22:38,243 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 17:22:41,302 [WARNING] in django.request: Not Found: /ru/
2024-05-03 18:25:21,916 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-03 18:25:24,317 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:11:29,405 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:11:32,529 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:11:32,763 [WARNING] in django.request: Not Found: /ru/favicon.ico
2024-05-08 14:11:44,464 [WARNING] in django.request: Not Found: /ru/shop/export/
2024-05-08 14:13:19,304 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-08 14:13:20,272 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:16:22,026 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\mysite\settings.py changed, reloading.
2024-05-08 14:16:23,129 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:16:57,356 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 14:16:57,397 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:16:58,217 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:16:58,310 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:17:13,762 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:17:13,876 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:17:35,693 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:17:35,766 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:17:39,310 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:17:39,393 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:17:57,598 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:19:30,352 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:19:30,469 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:19:57,518 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:20:26,780 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:20:28,597 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 14:20:28,619 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:20:29,254 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:20:29,358 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:20:37,128 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:20:37,246 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:21:28,753 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:26:51,651 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\mysite\settings.py changed, reloading.
2024-05-08 14:26:52,582 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:26:55,125 [WARNING] in django.request: Not Found: /
2024-05-08 14:26:55,128 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 14:26:55,836 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:27:14,128 [WARNING] in django.request: Not Found: /shop/products/export/
2024-05-08 14:27:14,253 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:27:17,057 [WARNING] in django.request: Not Found: /shop/products/export/
2024-05-08 14:27:17,231 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:27:28,601 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\mysite\settings.py changed, reloading.
2024-05-08 14:27:28,693 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:27:29,554 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:27:39,654 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 14:27:39,685 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:27:40,160 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:27:40,270 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:28:39,756 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:28:50,773 [WARNING] in django.request: Not Found: /ru/shop/products/export/
2024-05-08 14:28:50,920 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:29:39,759 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:02,720 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\urls.py changed, reloading.
2024-05-08 14:30:03,681 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 14:30:05,806 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 14:30:05,825 [WARNING] in django.request: Not Found: /ru/
2024-05-08 14:30:06,236 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:06,399 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:09,571 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:09,674 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:09,747 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:09,930 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:14,731 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "archived": product.archived,
                ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 14:30:14,801 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:30:15,002 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 14:31:06,007 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:23:44,754 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (2): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 15:23:45,587 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:23:45,780 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:23:45,850 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:23:54,386 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:01,214 [ERROR] in django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "archived": product.archived,
                ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:24:01,245 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:01,672 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:17,318 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:20,891 [WARNING] in django.request: Not Found: /ru/shop/export/
2024-05-08 15:24:20,927 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:21,255 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:30,022 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:38,909 [ERROR] in django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "archived": product.archived,
                ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:24:38,942 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:24:39,056 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:25:30,021 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:27:34,562 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-08 15:27:35,824 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 15:27:38,107 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 15:27:38,124 [WARNING] in django.request: Not Found: /ru/
2024-05-08 15:27:38,747 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:27:38,848 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:27:46,837 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:27:46,826 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:27:47,042 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:28:38,187 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:02,536 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:13,453 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:33:13,589 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:13,694 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:13,842 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:33:13,892 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:13,985 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:33:38,184 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:12,830 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:34:12,891 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:12,994 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:27,928 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:32,907 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 15:34:34,285 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 15:34:34,308 [WARNING] in django.request: Not Found: /ru/
2024-05-08 15:34:34,907 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:35,002 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:39,101 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:43,406 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:34:43,496 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:43,810 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:43,989 [WARNING] in django.request: Not Found: /ru/shop/products/export//
2024-05-08 15:34:44,121 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:46,617 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:34:47,097 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:47,258 [ERROR] in django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py", line 219, in get
    "is_archived": product.archived,
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'archived'. Did you mean: 'is_archived'?
2024-05-08 15:34:47,509 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:47,809 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:34:47,906 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:35:21,513 [INFO] in django.utils.autoreload: C:\Users\user\PycharmProjects\pythonProject\Django_project\mysite\shopapp\views.py changed, reloading.
2024-05-08 15:35:21,608 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:35:22,445 [INFO] in django.utils.autoreload: Watching for file changes with StatReloader
2024-05-08 15:35:23,940 [DEBUG] in urllib3.connectionpool: Starting new HTTPS connection (1): o4507220180795392.ingest.de.sentry.io:443
2024-05-08 15:35:23,971 [WARNING] in django.request: Not Found: /ru/
2024-05-08 15:35:24,479 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:35:24,564 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:35:29,171 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:35:31,831 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
2024-05-08 15:36:13,705 [DEBUG] in urllib3.connectionpool: https://o4507220180795392.ingest.de.sentry.io:443 "POST /api/4507220186693712/envelope/ HTTP/1.1" 200 0
